/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author POSITIVO
 */
public class TelaMeses extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMeses
     */
    public TelaMeses() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel46 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        js_mes = new javax.swing.JSpinner();
        bt_mes = new javax.swing.JButton();
        jp_bcgS = new javax.swing.JPanel();
        jp_hepS = new javax.swing.JPanel();
        jp_pentaS = new javax.swing.JPanel();
        jp_vipS = new javax.swing.JPanel();
        jp_pneS = new javax.swing.JPanel();
        jp_rotaS = new javax.swing.JPanel();
        jp_meniS = new javax.swing.JPanel();
        jp_febreS = new javax.swing.JPanel();
        jp_triS = new javax.swing.JPanel();
        jp_bcgN = new javax.swing.JPanel();
        jp_vipN = new javax.swing.JPanel();
        jp_pentaN = new javax.swing.JPanel();
        jp_febreN = new javax.swing.JPanel();
        jp_triN = new javax.swing.JPanel();
        jp_pneN = new javax.swing.JPanel();
        jp_meniN = new javax.swing.JPanel();
        jp_hepN = new javax.swing.JPanel();
        jp_rotaN = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_bcg = new javax.swing.JLabel();
        lb_febre = new javax.swing.JLabel();
        lb_tri = new javax.swing.JLabel();
        lb_meni = new javax.swing.JLabel();
        lb_rota = new javax.swing.JLabel();
        lb_pne = new javax.swing.JLabel();
        lb_vip = new javax.swing.JLabel();
        lb_penta = new javax.swing.JLabel();
        lb_hep = new javax.swing.JLabel();

        jLabel46.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel46.setText("-");

        setTitle("Tabela de Meses");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setForeground(new java.awt.Color(0, 102, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vacinas de 0 á 12 meses");

        js_mes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        js_mes.setModel(new javax.swing.SpinnerNumberModel(0, 0, 12, 1));

        bt_mes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        bt_mes.setText("Ok");
        bt_mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                .addComponent(js_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(bt_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_mes)
                    .addComponent(js_mes, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 12, 960, -1));

        javax.swing.GroupLayout jp_bcgSLayout = new javax.swing.GroupLayout(jp_bcgS);
        jp_bcgS.setLayout(jp_bcgSLayout);
        jp_bcgSLayout.setHorizontalGroup(
            jp_bcgSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_bcgSLayout.setVerticalGroup(
            jp_bcgSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_bcgS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 70, 30));

        javax.swing.GroupLayout jp_hepSLayout = new javax.swing.GroupLayout(jp_hepS);
        jp_hepS.setLayout(jp_hepSLayout);
        jp_hepSLayout.setHorizontalGroup(
            jp_hepSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_hepSLayout.setVerticalGroup(
            jp_hepSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_hepS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        javax.swing.GroupLayout jp_pentaSLayout = new javax.swing.GroupLayout(jp_pentaS);
        jp_pentaS.setLayout(jp_pentaSLayout);
        jp_pentaSLayout.setHorizontalGroup(
            jp_pentaSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_pentaSLayout.setVerticalGroup(
            jp_pentaSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_pentaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        javax.swing.GroupLayout jp_vipSLayout = new javax.swing.GroupLayout(jp_vipS);
        jp_vipS.setLayout(jp_vipSLayout);
        jp_vipSLayout.setHorizontalGroup(
            jp_vipSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_vipSLayout.setVerticalGroup(
            jp_vipSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_vipS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        javax.swing.GroupLayout jp_pneSLayout = new javax.swing.GroupLayout(jp_pneS);
        jp_pneS.setLayout(jp_pneSLayout);
        jp_pneSLayout.setHorizontalGroup(
            jp_pneSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_pneSLayout.setVerticalGroup(
            jp_pneSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_pneS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        javax.swing.GroupLayout jp_rotaSLayout = new javax.swing.GroupLayout(jp_rotaS);
        jp_rotaS.setLayout(jp_rotaSLayout);
        jp_rotaSLayout.setHorizontalGroup(
            jp_rotaSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_rotaSLayout.setVerticalGroup(
            jp_rotaSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_rotaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        javax.swing.GroupLayout jp_meniSLayout = new javax.swing.GroupLayout(jp_meniS);
        jp_meniS.setLayout(jp_meniSLayout);
        jp_meniSLayout.setHorizontalGroup(
            jp_meniSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_meniSLayout.setVerticalGroup(
            jp_meniSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_meniS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        javax.swing.GroupLayout jp_febreSLayout = new javax.swing.GroupLayout(jp_febreS);
        jp_febreS.setLayout(jp_febreSLayout);
        jp_febreSLayout.setHorizontalGroup(
            jp_febreSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_febreSLayout.setVerticalGroup(
            jp_febreSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_febreS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, -1));

        javax.swing.GroupLayout jp_triSLayout = new javax.swing.GroupLayout(jp_triS);
        jp_triS.setLayout(jp_triSLayout);
        jp_triSLayout.setHorizontalGroup(
            jp_triSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_triSLayout.setVerticalGroup(
            jp_triSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_triS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        javax.swing.GroupLayout jp_bcgNLayout = new javax.swing.GroupLayout(jp_bcgN);
        jp_bcgN.setLayout(jp_bcgNLayout);
        jp_bcgNLayout.setHorizontalGroup(
            jp_bcgNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_bcgNLayout.setVerticalGroup(
            jp_bcgNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_bcgN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        javax.swing.GroupLayout jp_vipNLayout = new javax.swing.GroupLayout(jp_vipN);
        jp_vipN.setLayout(jp_vipNLayout);
        jp_vipNLayout.setHorizontalGroup(
            jp_vipNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_vipNLayout.setVerticalGroup(
            jp_vipNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_vipN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        javax.swing.GroupLayout jp_pentaNLayout = new javax.swing.GroupLayout(jp_pentaN);
        jp_pentaN.setLayout(jp_pentaNLayout);
        jp_pentaNLayout.setHorizontalGroup(
            jp_pentaNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_pentaNLayout.setVerticalGroup(
            jp_pentaNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_pentaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        javax.swing.GroupLayout jp_febreNLayout = new javax.swing.GroupLayout(jp_febreN);
        jp_febreN.setLayout(jp_febreNLayout);
        jp_febreNLayout.setHorizontalGroup(
            jp_febreNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_febreNLayout.setVerticalGroup(
            jp_febreNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_febreN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        javax.swing.GroupLayout jp_triNLayout = new javax.swing.GroupLayout(jp_triN);
        jp_triN.setLayout(jp_triNLayout);
        jp_triNLayout.setHorizontalGroup(
            jp_triNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_triNLayout.setVerticalGroup(
            jp_triNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_triN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, -1, -1));

        javax.swing.GroupLayout jp_pneNLayout = new javax.swing.GroupLayout(jp_pneN);
        jp_pneN.setLayout(jp_pneNLayout);
        jp_pneNLayout.setHorizontalGroup(
            jp_pneNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_pneNLayout.setVerticalGroup(
            jp_pneNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_pneN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        javax.swing.GroupLayout jp_meniNLayout = new javax.swing.GroupLayout(jp_meniN);
        jp_meniN.setLayout(jp_meniNLayout);
        jp_meniNLayout.setHorizontalGroup(
            jp_meniNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_meniNLayout.setVerticalGroup(
            jp_meniNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_meniN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        javax.swing.GroupLayout jp_hepNLayout = new javax.swing.GroupLayout(jp_hepN);
        jp_hepN.setLayout(jp_hepNLayout);
        jp_hepNLayout.setHorizontalGroup(
            jp_hepNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_hepNLayout.setVerticalGroup(
            jp_hepNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_hepN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 70, 30));

        javax.swing.GroupLayout jp_rotaNLayout = new javax.swing.GroupLayout(jp_rotaN);
        jp_rotaN.setLayout(jp_rotaNLayout);
        jp_rotaNLayout.setHorizontalGroup(
            jp_rotaNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_rotaNLayout.setVerticalGroup(
            jp_rotaNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_rotaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("BCG");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("VACINA");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("Hepatite B");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("Penta");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setText("VIP");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setText("Pneumocócica 10v");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setText("Rotavírus");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setText("Meningocócica");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setText("Febre Amarela");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel22.setText("Tríplice Viral");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 153));
        jLabel23.setText("TOMOU?");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setText("SIM");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 0, 51));
        jLabel25.setText("NÃO");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 102));
        jLabel26.setText("SIM");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 0, 51));
        jLabel27.setText("NÃO");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 102));
        jLabel28.setText("SIM");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 0, 51));
        jLabel29.setText("NÃO");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 102));
        jLabel30.setText("SIM");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(153, 0, 51));
        jLabel31.setText("NÃO");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, -1, -1));

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 102, 102));
        jLabel32.setText("SIM");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(153, 0, 51));
        jLabel33.setText("NÃO");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 102, 102));
        jLabel34.setText("SIM");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 0, 51));
        jLabel35.setText("NÃO");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 102, 102));
        jLabel36.setText("SIM");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(153, 0, 51));
        jLabel37.setText("NÃO");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 102, 102));
        jLabel38.setText("SIM");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(153, 0, 51));
        jLabel39.setText("NÃO");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 102, 102));
        jLabel40.setText("SIM");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(153, 0, 51));
        jLabel41.setText("NÃO");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 16, 330));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 16, 330));

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 153, 153));
        jLabel42.setText("TIPO(específico)");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 464, -1, -1));

        lb_bcg.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_bcg.setText("-");
        getContentPane().add(lb_bcg, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 258, -1));

        lb_febre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_febre.setText("-");
        getContentPane().add(lb_febre, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 258, -1));

        lb_tri.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_tri.setText("-");
        getContentPane().add(lb_tri, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 258, -1));

        lb_meni.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_meni.setText("-");
        getContentPane().add(lb_meni, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 258, -1));

        lb_rota.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_rota.setText("-");
        getContentPane().add(lb_rota, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 258, -1));

        lb_pne.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_pne.setText("-");
        getContentPane().add(lb_pne, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 258, -1));

        lb_vip.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_vip.setText("-");
        getContentPane().add(lb_vip, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 258, -1));

        lb_penta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_penta.setText("-");
        getContentPane().add(lb_penta, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 258, -1));

        lb_hep.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_hep.setText("-");
        getContentPane().add(lb_hep, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 258, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mesActionPerformed
        int mes = (int) js_mes.getValue();
        verificador(mes);
    }//GEN-LAST:event_bt_mesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_mes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jp_bcgN;
    private javax.swing.JPanel jp_bcgS;
    private javax.swing.JPanel jp_febreN;
    private javax.swing.JPanel jp_febreS;
    private javax.swing.JPanel jp_hepN;
    private javax.swing.JPanel jp_hepS;
    private javax.swing.JPanel jp_meniN;
    private javax.swing.JPanel jp_meniS;
    private javax.swing.JPanel jp_pentaN;
    private javax.swing.JPanel jp_pentaS;
    private javax.swing.JPanel jp_pneN;
    private javax.swing.JPanel jp_pneS;
    private javax.swing.JPanel jp_rotaN;
    private javax.swing.JPanel jp_rotaS;
    private javax.swing.JPanel jp_triN;
    private javax.swing.JPanel jp_triS;
    private javax.swing.JPanel jp_vipN;
    private javax.swing.JPanel jp_vipS;
    private javax.swing.JSpinner js_mes;
    private javax.swing.JLabel lb_bcg;
    private javax.swing.JLabel lb_febre;
    private javax.swing.JLabel lb_hep;
    private javax.swing.JLabel lb_meni;
    private javax.swing.JLabel lb_penta;
    private javax.swing.JLabel lb_pne;
    private javax.swing.JLabel lb_rota;
    private javax.swing.JLabel lb_tri;
    private javax.swing.JLabel lb_vip;
    // End of variables declaration//GEN-END:variables

    public void verificador(int mes){
        switch(mes){
            case 0: tomou(false, false, true, true, true, true, true, true, true);
            tipo("dose única", "dose ao nascer", "-", "-", "-", "-", "-", "-", "-");
            break;
            
            case 1:tomou(false, false, true, true, true, true, true, true, true);
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-");
            break;
            
            case 2:tomou(false, false, false, false, false, false, true, true, true);
            tipo("-", "-", "primeira dose", "primeira dose", "primeira dose", "primeira dose", "-", "-", "-");
            break;
            
            case 3:tomou(false, false, false, false, false, false, false, true, true);
            tipo("-", "-", "-", "-", "-", "-", "primeira dose", "-", "-");
            break;
            
            case 4:tomou(false, false, false, false, false, false, false, true, true);
            tipo("-", "-", "segunda dose", "segunda dose", "segunda dose", "segunda dose", "-", "-", "-");
            break;
            
            case 5:tomou(false, false, false, false, false, false, false, true, true);
            tipo("-", "-", "-", "-", "-", "-", "segunda dose", "-", "-");
            break;
            
            case 6:tomou(false, false, false, false, false, false, false, true, true);
            tipo("-", "-", "terceira dose", "terceira dose", "-", "-", "-", "-", "-");
            break;
            
            case 7:tomou(false, false, false, false, false, false, false, true, true);
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-");
            break;
            
            case 8:tomou(false, false, false, false, false, false, false, true, true);
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-");
            break;
            
            case 9:tomou(false, false, false, false, false, false, false, false, true);
            tipo("-", "-", "-", "-", "-", "-", "-", "dose inicial", "-");
            break;
            
            case 10:tomou(false, false, false, false, false, false, false, false, true);
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-");
            break;
            
            case 11:tomou(false, false, false, false, false, false, false, false, true);
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-");
            break;
            
            case 12:tomou(false, false, false, false, false, false, false, false, false);
            tipo("-", "-", "-", "-", "reforço", "-", "reforço", "-", "primeira dose");
            break;
        }
    }
    
    public void tomou(boolean a, boolean b, boolean c, boolean d, boolean e, boolean f, boolean g, boolean h, boolean i){
    jp_bcgS.setVisible(a);
    jp_hepS.setVisible(b);
    jp_pentaS.setVisible(c);
    jp_vipS.setVisible(d);
    jp_pneS.setVisible(e);
    jp_rotaS.setVisible(f);
    jp_meniS.setVisible(g);
    jp_febreS.setVisible(h);
    jp_triS.setVisible(i);
    
    jp_bcgN.setVisible(!a);
    jp_hepN.setVisible(!b);
    jp_pentaN.setVisible(!c);
    jp_vipN.setVisible(!d);
    jp_pneN.setVisible(!e);
    jp_rotaN.setVisible(!f);
    jp_meniN.setVisible(!g);
    jp_febreN.setVisible(!h);
    jp_triN.setVisible(!i);
    }
    public void tipo(String a, String b, String c, String d, String e, String f, String g, String h, String i){
    lb_bcg.setText(a);
    lb_hep.setText(b);
    lb_penta.setText(c);
    lb_vip.setText(d);
    lb_pne.setText(e);
    lb_rota.setText(f);
    lb_meni.setText(g);
    lb_febre.setText(h);
    lb_tri.setText(i);
    }

}
