/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author POSITIVO
 */
public class TelaAnos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaMeses
     */
    public TelaAnos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel46 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        js_ano = new javax.swing.JSpinner();
        bt_ano = new javax.swing.JButton();
        jp_pentaS = new javax.swing.JPanel();
        jp_vopS = new javax.swing.JPanel();
        jp_treS = new javax.swing.JPanel();
        jp_hepaS = new javax.swing.JPanel();
        jp_variS = new javax.swing.JPanel();
        jp_febreS = new javax.swing.JPanel();
        jp_hpvS = new javax.swing.JPanel();
        jp_hepbS = new javax.swing.JPanel();
        jp_triS = new javax.swing.JPanel();
        jp_pentaN = new javax.swing.JPanel();
        jp_hepaN = new javax.swing.JPanel();
        jp_treN = new javax.swing.JPanel();
        jp_hepbN = new javax.swing.JPanel();
        jp_triN = new javax.swing.JPanel();
        jp_variN = new javax.swing.JPanel();
        jp_hpvN = new javax.swing.JPanel();
        jp_vopN = new javax.swing.JPanel();
        jp_febreN = new javax.swing.JPanel();
        jp_duplaS = new javax.swing.JPanel();
        jp_duplaN = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel42 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lb_penta = new javax.swing.JLabel();
        lb_hepb = new javax.swing.JLabel();
        lb_tri = new javax.swing.JLabel();
        lb_hpv = new javax.swing.JLabel();
        lb_febre = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        lb_vari = new javax.swing.JLabel();
        lb_hepa = new javax.swing.JLabel();
        lb_tre = new javax.swing.JLabel();
        lb_vop = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        lb_dupla = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();

        jLabel46.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel46.setText("-");

        setTitle("Tabela de Anos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setForeground(new java.awt.Color(153, 255, 153));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vacinas de 1 á 60+ anos");

        js_ano.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        js_ano.setModel(new javax.swing.SpinnerNumberModel(1, 1, 130, 1));

        bt_ano.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        bt_ano.setText("Ok");
        bt_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_anoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addComponent(js_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(bt_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_ano)
                    .addComponent(js_ano, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 15, 950, 120));

        javax.swing.GroupLayout jp_pentaSLayout = new javax.swing.GroupLayout(jp_pentaS);
        jp_pentaS.setLayout(jp_pentaSLayout);
        jp_pentaSLayout.setHorizontalGroup(
            jp_pentaSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_pentaSLayout.setVerticalGroup(
            jp_pentaSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_pentaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 70, 30));

        javax.swing.GroupLayout jp_vopSLayout = new javax.swing.GroupLayout(jp_vopS);
        jp_vopS.setLayout(jp_vopSLayout);
        jp_vopSLayout.setHorizontalGroup(
            jp_vopSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_vopSLayout.setVerticalGroup(
            jp_vopSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_vopS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, -1));

        javax.swing.GroupLayout jp_treSLayout = new javax.swing.GroupLayout(jp_treS);
        jp_treS.setLayout(jp_treSLayout);
        jp_treSLayout.setHorizontalGroup(
            jp_treSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_treSLayout.setVerticalGroup(
            jp_treSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_treS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        javax.swing.GroupLayout jp_hepaSLayout = new javax.swing.GroupLayout(jp_hepaS);
        jp_hepaS.setLayout(jp_hepaSLayout);
        jp_hepaSLayout.setHorizontalGroup(
            jp_hepaSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_hepaSLayout.setVerticalGroup(
            jp_hepaSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_hepaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, -1));

        javax.swing.GroupLayout jp_variSLayout = new javax.swing.GroupLayout(jp_variS);
        jp_variS.setLayout(jp_variSLayout);
        jp_variSLayout.setHorizontalGroup(
            jp_variSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_variSLayout.setVerticalGroup(
            jp_variSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_variS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, -1));

        javax.swing.GroupLayout jp_febreSLayout = new javax.swing.GroupLayout(jp_febreS);
        jp_febreS.setLayout(jp_febreSLayout);
        jp_febreSLayout.setHorizontalGroup(
            jp_febreSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_febreSLayout.setVerticalGroup(
            jp_febreSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_febreS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, -1));

        javax.swing.GroupLayout jp_hpvSLayout = new javax.swing.GroupLayout(jp_hpvS);
        jp_hpvS.setLayout(jp_hpvSLayout);
        jp_hpvSLayout.setHorizontalGroup(
            jp_hpvSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_hpvSLayout.setVerticalGroup(
            jp_hpvSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_hpvS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        javax.swing.GroupLayout jp_hepbSLayout = new javax.swing.GroupLayout(jp_hepbS);
        jp_hepbS.setLayout(jp_hepbSLayout);
        jp_hepbSLayout.setHorizontalGroup(
            jp_hepbSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_hepbSLayout.setVerticalGroup(
            jp_hepbSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_hepbS, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, -1, -1));

        javax.swing.GroupLayout jp_triSLayout = new javax.swing.GroupLayout(jp_triS);
        jp_triS.setLayout(jp_triSLayout);
        jp_triSLayout.setHorizontalGroup(
            jp_triSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_triSLayout.setVerticalGroup(
            jp_triSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_triS, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, -1));

        javax.swing.GroupLayout jp_pentaNLayout = new javax.swing.GroupLayout(jp_pentaN);
        jp_pentaN.setLayout(jp_pentaNLayout);
        jp_pentaNLayout.setHorizontalGroup(
            jp_pentaNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_pentaNLayout.setVerticalGroup(
            jp_pentaNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_pentaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        javax.swing.GroupLayout jp_hepaNLayout = new javax.swing.GroupLayout(jp_hepaN);
        jp_hepaN.setLayout(jp_hepaNLayout);
        jp_hepaNLayout.setHorizontalGroup(
            jp_hepaNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_hepaNLayout.setVerticalGroup(
            jp_hepaNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_hepaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        javax.swing.GroupLayout jp_treNLayout = new javax.swing.GroupLayout(jp_treN);
        jp_treN.setLayout(jp_treNLayout);
        jp_treNLayout.setHorizontalGroup(
            jp_treNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_treNLayout.setVerticalGroup(
            jp_treNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_treN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));

        javax.swing.GroupLayout jp_hepbNLayout = new javax.swing.GroupLayout(jp_hepbN);
        jp_hepbN.setLayout(jp_hepbNLayout);
        jp_hepbNLayout.setHorizontalGroup(
            jp_hepbNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_hepbNLayout.setVerticalGroup(
            jp_hepbNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_hepbN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, -1, -1));

        javax.swing.GroupLayout jp_triNLayout = new javax.swing.GroupLayout(jp_triN);
        jp_triN.setLayout(jp_triNLayout);
        jp_triNLayout.setHorizontalGroup(
            jp_triNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_triNLayout.setVerticalGroup(
            jp_triNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_triN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, -1, -1));

        javax.swing.GroupLayout jp_variNLayout = new javax.swing.GroupLayout(jp_variN);
        jp_variN.setLayout(jp_variNLayout);
        jp_variNLayout.setHorizontalGroup(
            jp_variNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_variNLayout.setVerticalGroup(
            jp_variNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_variN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, -1));

        javax.swing.GroupLayout jp_hpvNLayout = new javax.swing.GroupLayout(jp_hpvN);
        jp_hpvN.setLayout(jp_hpvNLayout);
        jp_hpvNLayout.setHorizontalGroup(
            jp_hpvNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_hpvNLayout.setVerticalGroup(
            jp_hpvNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        getContentPane().add(jp_hpvN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, 70, -1));

        javax.swing.GroupLayout jp_vopNLayout = new javax.swing.GroupLayout(jp_vopN);
        jp_vopN.setLayout(jp_vopNLayout);
        jp_vopNLayout.setHorizontalGroup(
            jp_vopNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_vopNLayout.setVerticalGroup(
            jp_vopNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_vopN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 70, 30));

        javax.swing.GroupLayout jp_febreNLayout = new javax.swing.GroupLayout(jp_febreN);
        jp_febreN.setLayout(jp_febreNLayout);
        jp_febreNLayout.setHorizontalGroup(
            jp_febreNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_febreNLayout.setVerticalGroup(
            jp_febreNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jp_febreN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        javax.swing.GroupLayout jp_duplaSLayout = new javax.swing.GroupLayout(jp_duplaS);
        jp_duplaS.setLayout(jp_duplaSLayout);
        jp_duplaSLayout.setHorizontalGroup(
            jp_duplaSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_duplaSLayout.setVerticalGroup(
            jp_duplaSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        getContentPane().add(jp_duplaS, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        javax.swing.GroupLayout jp_duplaNLayout = new javax.swing.GroupLayout(jp_duplaN);
        jp_duplaN.setLayout(jp_duplaNLayout);
        jp_duplaNLayout.setHorizontalGroup(
            jp_duplaNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        jp_duplaNLayout.setVerticalGroup(
            jp_duplaNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        getContentPane().add(jp_duplaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 450, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("Penta");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 153));
        jLabel13.setText("VACINA");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("VOP");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("Tretra Viral");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setText("Hepatite A");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setText("Varicela");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setText("Febre Amarela");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setText("HPV");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setText("Hepatite B");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel22.setText("Tríplice Viral");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 153, 153));
        jLabel23.setText("TOMOU?");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, -1, -1));

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 102, 102));
        jLabel24.setText("SIM");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 0, 51));
        jLabel25.setText("NÃO");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 102, 102));
        jLabel26.setText("SIM");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(153, 0, 51));
        jLabel27.setText("NÃO");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, -1, -1));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 102));
        jLabel28.setText("SIM");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(153, 0, 51));
        jLabel29.setText("NÃO");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 400, -1, -1));

        jLabel32.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 102, 102));
        jLabel32.setText("SIM");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        jLabel33.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(153, 0, 51));
        jLabel33.setText("NÃO");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, -1, -1));

        jLabel34.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 102, 102));
        jLabel34.setText("SIM");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, -1, -1));

        jLabel35.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(153, 0, 51));
        jLabel35.setText("NÃO");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        jLabel36.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 102, 102));
        jLabel36.setText("SIM");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, -1, -1));

        jLabel37.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(153, 0, 51));
        jLabel37.setText("NÃO");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 102, 102));
        jLabel38.setText("SIM");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel39.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(153, 0, 51));
        jLabel39.setText("NÃO");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        jLabel40.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 102, 102));
        jLabel40.setText("SIM");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel41.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(153, 0, 51));
        jLabel41.setText("NÃO");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 16, 360));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 16, 360));

        jLabel42.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(0, 153, 153));
        jLabel42.setText("TIPO(específico)");
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 140, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(896, 464, -1, -1));

        lb_penta.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_penta.setText("-");
        getContentPane().add(lb_penta, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 190, 258, -1));

        lb_hepb.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_hepb.setText("-");
        getContentPane().add(lb_hepb, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, 258, -1));

        lb_tri.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_tri.setText("-");
        getContentPane().add(lb_tri, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 430, 258, -1));

        lb_hpv.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_hpv.setText("-");
        getContentPane().add(lb_hpv, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, 258, -1));

        lb_febre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_febre.setText("-");
        getContentPane().add(lb_febre, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 258, -1));

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 102));
        jLabel30.setText("SIM");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        lb_vari.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_vari.setText("-");
        getContentPane().add(lb_vari, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 258, -1));

        lb_hepa.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_hepa.setText("-");
        getContentPane().add(lb_hepa, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 258, -1));

        lb_tre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_tre.setText("-");
        getContentPane().add(lb_tre, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 250, 258, -1));

        lb_vop.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_vop.setText("-");
        getContentPane().add(lb_vop, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 258, -1));

        jLabel43.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel43.setText("Dupla Adulto");
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        lb_dupla.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_dupla.setText("-");
        getContentPane().add(lb_dupla, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, 258, -1));

        jLabel44.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 102, 102));
        jLabel44.setText("SIM");
        getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, -1, -1));

        jLabel45.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(153, 0, 51));
        jLabel45.setText("NÃO");
        getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, -1, -1));

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(153, 0, 51));
        jLabel31.setText("NÃO");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_anoActionPerformed
        int ano = (int)js_ano.getValue();
        verificador(ano);
    }//GEN-LAST:event_bt_anoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ano;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jp_duplaN;
    private javax.swing.JPanel jp_duplaS;
    private javax.swing.JPanel jp_febreN;
    private javax.swing.JPanel jp_febreS;
    private javax.swing.JPanel jp_hepaN;
    private javax.swing.JPanel jp_hepaS;
    private javax.swing.JPanel jp_hepbN;
    private javax.swing.JPanel jp_hepbS;
    private javax.swing.JPanel jp_hpvN;
    private javax.swing.JPanel jp_hpvS;
    private javax.swing.JPanel jp_pentaN;
    private javax.swing.JPanel jp_pentaS;
    private javax.swing.JPanel jp_treN;
    private javax.swing.JPanel jp_treS;
    private javax.swing.JPanel jp_triN;
    private javax.swing.JPanel jp_triS;
    private javax.swing.JPanel jp_variN;
    private javax.swing.JPanel jp_variS;
    private javax.swing.JPanel jp_vopN;
    private javax.swing.JPanel jp_vopS;
    private javax.swing.JSpinner js_ano;
    private javax.swing.JLabel lb_dupla;
    private javax.swing.JLabel lb_febre;
    private javax.swing.JLabel lb_hepa;
    private javax.swing.JLabel lb_hepb;
    private javax.swing.JLabel lb_hpv;
    private javax.swing.JLabel lb_penta;
    private javax.swing.JLabel lb_tre;
    private javax.swing.JLabel lb_tri;
    private javax.swing.JLabel lb_vari;
    private javax.swing.JLabel lb_vop;
    // End of variables declaration//GEN-END:variables

    public void verificador(int ano){
        if (ano<=2) {
            tomou(false, false, false, false, true, false, true, false, false, true);
            tipo("reforço com DTP", "reforço", "dose única", "dose única", "-", "-", "-", "-", "-", "-");
        } else if(ano>2 && ano<=4){
            tomou(false, false, false, false, true, false, true, false, false, true);
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-", "-");
            if(ano==4){
            tomou(false, false, false, false, false, false, true, false, false, true);
            tipo("reforço com DTP", "reforço", "-", "-", "-", "-", "-", "-", "-", "-");
            }
        } else if(ano>4 && ano<=9){
            tomou(false, false, false, false, false, false, true, false, false, true);
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-", "-");
            if(ano==9){
            tomou(false, false, false, false, false, false, false, false, false, true);
            tipo("-", "-", "-", "-", "-", "-", "1 dose", "-", "-", "-");
            }
        } else if(ano>9 && ano<=20) {
            tomou(false, false, false, false, false, false, false, false, false, true);
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-", "-");
            if(ano==20){
            tomou(false, false, false, false, false, false, false, false, false, false);
            tipo("-", "-", "-", "-", "-", "-", "2 doses", "3 doses", "segunda dose", "reforço a cada 10 anos");
            }
        } else if(ano>20 && ano<60){
            tomou(false, false, false, false, false, false, false, false, false, false);
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-", "-");
            if (ano==30){
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-", "reforço a cada 10 anos");
            } else if (ano==40){
            
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-", "reforço a cada 10 anos");
            }else if (ano==50){
            
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "1 dose", "reforço a cada 10 anos");
        } }else if(ano>=60 && ano<=130) {
            tomou(false, false, false, false, false, false, false, false, false, false);
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-", "-");
            if(ano==60){
            tipo("-", "-", "-", "-", "-", "-", "-", "3 doses", "-", "reforço a cada 10 anos");
            }
            if(ano==70){
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-", "reforço a cada 10 anos");
            }
            if(ano==80){
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-", "reforço a cada 10 anos");
            }
            if(ano==90){
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-", "reforço a cada 10 anos");
            }
            if(ano==100){
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-", "reforço a cada 10 anos");
            }
            if(ano==110){
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-", "reforço a cada 10 anos");
            }
            if(ano==120){
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-", "reforço a cada 10 anos");
            }
            if(ano==130){
            tipo("-", "-", "-", "-", "-", "-", "-", "-", "-", "reforço a cada 10 anos");
            }
        }
    }
    
    public void tomou(boolean a, boolean b, boolean c, boolean d, boolean e, boolean f, boolean g, boolean h, boolean i, boolean j){
    jp_pentaS.setVisible(a);
    jp_vopS.setVisible(b);
    jp_treS.setVisible(c);
    jp_hepaS.setVisible(d);
    jp_variS.setVisible(e);
    jp_febreS.setVisible(f);
    jp_hpvS.setVisible(g);
    jp_hepbS.setVisible(h);
    jp_triS.setVisible(i);
    jp_duplaS.setVisible(j);
    
    jp_pentaN.setVisible(!a);
    jp_vopN.setVisible(!b);
    jp_treN.setVisible(!c);
    jp_hepaN.setVisible(!d);
    jp_variN.setVisible(!e);
    jp_febreN.setVisible(!f);
    jp_hpvN.setVisible(!g);
    jp_hepbN.setVisible(!h);
    jp_triN.setVisible(!i);
    jp_duplaN.setVisible(!j);
    }
    public void tipo(String a, String b, String c, String d, String e, String f, String g, String h, String i, String j){
    lb_penta.setText(a);
    lb_vop.setText(b);
    lb_tre.setText(c);
    lb_hepa.setText(d);
    lb_vari.setText(e);
    lb_febre.setText(f);
    lb_hpv.setText(g);
    lb_hepb.setText(h);
    lb_tri.setText(i);
    lb_dupla.setText(j);
    }

}
